### ISSUE TITLE
cudatoolkit-dev installation pops up a terminal window

### ISSUE THREAD

**Issue by pearu** [conda-forge/cudatoolkit-dev-feedstock#7]
Issue: When running `conda install cudatoolkit-dev -c conda-forge`, a new terminal window is opened with a title 'NVIDIA CUDA PACKAGE' and one needs to wait for "Press Return to close this window..." message, otherwise the installation will fail.

Expected behavior: `conda install ...` would not use any graphical tools.

When resetting (`DISPLAY=`), no window will pop up and the installation seems to be successful (there are no errors or warnings from conda).

**Comment by pearu** [comment]
I was hit by this issue again. Would it be possible to set `DISPLAY=` within `cudatoolkit-dev` installation scripts?

**Comment by andersy005** [comment]
@pearu, 

I am not familiar with the `DISPLAY` setting, and I am wondering if you could tell me where this would go within `cudatoolkit-dev`? From past experience, the pop up window appears on Linux and not on OSX.

**Comment by pearu** [comment]
@andersy005 , see https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/master/recipe/cudatoolkit-dev-post-install.py#L183 : 
Using
```
subprocess.check_call(cmd, env=dict(DISPLAY=''))
```
should work.

**Comment by farleylai** [comment]
The terminal requires hitting ENTER to close it which seems unnecessary and users may wait for this unexpected behavior INDEFINITELY if the window is not in the foreground to be noticeable.

**Comment by andersy005** [comment]
@farleylai, this issue is fixed in #16. However, #16 hasn't been merged yet.

**Comment by andersy005** [comment]
@pearu, can you confirm that this issue was resolved in #16?

**Comment by pearu** [comment]
Yes, I'll test it once it will be uploaded to conda-forge.

**Comment by pearu** [comment]
No, the issue still exists.
![Screenshot from 2019-10-01 23-35-07](https://user-images.githubusercontent.com/402156/65998631-5e566300-e4a4-11e9-93bc-61acd90a7cdf.png)
I'll test the DISPLAY trick again, the earlier suggestion `subprocess.check_call(cmd, env=dict(DISPLAY=''))` did not work because it cleared up all the environment for `cmd`.

**Comment by andersy005** [comment]
Can we copy the env and pass it to subprocess with:
```python
import os
my_env = os.environ.copy()
my_env['DISPLAY'] = ''
subprocess.check_call(cmd, env=my_env)
```
?

**Comment by pearu** [comment]
IIRC, I tried that, did not worked but at the time there were multiple issues.

I am currently testing
```
import os
os.environ['DISPLAY'] = ''
```

**Comment by pearu** [comment]
Fix confirmed.

**Comment by davidrpugh** [comment]
I am still seeing this issue when trying to install `cudatoolkit-dev=10.0=py36` on Ubuntu 16.04. Both the other builds available for `cudatoolkit-dev=10.0` fail with the following error message.
```
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.0-2'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-10.0-2
location of failed script: /home/pughdr/Desktop/test-env/env/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/pughdr/Desktop/test-env/env/bin/cudatoolkit-dev-post-install.py", line 44, in <module>
    from conda.exports import download, hashsum_file
ModuleNotFoundError: No module named 'conda'

return code: 1

()
```

This issue does not exist for `cudatoolkit-dev=10.1`.

**Comment by pearu** [comment]
I would suggest not using `cudatoolkit-dev` at all as the used approach has some flaws that cannot be fixed (licensing).
Instead, install cudatoolkit from nvidia to your system and use conda package nvcc_linux-64 for building cuda sources.

**Comment by davidrpugh** [comment]
Looks like `nvcc_linux-64` targets CUDA 10.1 or am I mistaken?

**Comment by pearu** [comment]
No, you can use it with any CUDA version installed in your system. For instance, use `nvcc_linux-64=10.0` for CUDA 10.0.

**Comment by davidrpugh** [comment]
OK. I frequently use `conda` to install other NVIDIA libs for my project such as `cudnn`, `cupti`, and `nccl`. Is the recommended practice to also now download these from NVIDIA when using `nvcc_linux-64`?
